import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../src/components/header/Header'
const inter = Inter({ subsets: ['latin'] })
import Hero from '../src/components/hero/Hero'
import Sidebar from '../src/components/sidebar/Sidebar'
import Experience from '../src/components/experience/Experience'
import Skills from '../src/components/skills/Skills'
import { motion } from 'framer-motion'
import Example from '../src/components/Example'
import About from '../src/components/about/About'
import Projects from '../src/components/projects/Projects'
import ContactMe from '../src/components/contact/ContactMe'
import Certificate from '../src/components/certificates/Certificate'
export default function Home() {
  return (
    <div className='felx flex-col md:snap-y md:snap-mandatory bg-[#242424] text-white overflow-y-scroll
     overflow-x-hidden h-screen scrollbar scrollbar-thumb-amber-500 scrollbar-track-[#3C3C3C]  '>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-blue-900 bg-blue-500'>This is Home</div> */}
      {/* <div className='w-1/6 fixed flex flex-col h-full border-8 border-blue-500'>
        <h1 className='text-black'>Sidebar</h1>
            <h1>Sidebar</h1>
        </div> */}
      <Header />
      <div className='relative flex w-full'>
        <div className='w-1/12 h-full fixed  md:flex hidden items-center  z-20'>
          {/* <motion.div initial={{ x: -500, opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{ duration: 1.5 }}
           className='w-full h-2/5 flex flex-col justify-center items-center gap-4 bg-white bg-opacity-10 rounded-lg border'>
            <h1>About</h1>
            <a href="#About">About</a>
            <a href="#Experience">Experience</a>
            <a href="#Skills">Skills</a>
            <a href="#Projects">Projects</a>
            <a href="#Contact">Contact</a>
            
        </motion.div> */}
        </div>
        <div className='w-full flex flex-col'>
          <section id='Hero' className='snap-start'>
            <Hero />
          </section>
          <section id='About' className='snap-start'>
            <About />
          </section>
          <section id='Experience' className='snap-start'>
            <Experience />
          </section>
          <section id='Skills' className='snap-start'>
            <Skills />
          </section>
          <section id='Projects' className='snap-start'>
            <Projects />
          </section>
          <section id='Certificate' className='snap-start'>
            <Certificate />
          </section>
          <section id='Contact' className='snap-start'>
            <ContactMe />
          </section>
        </div>
      </div>
    </div>
  )
}
